changesetIgnorePatterns:
  - "**/*.tsbuildinfo"

compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

nodeLinker: pnp

preferInteractive: true

progressBarStyle: patrick

defaultSemverRangePrefix: ""
