# Yarn Berry (PnP) configuration for drifellascape
nodeLinker: pnp

# Privacy & performance
enableTelemetry: false
enableGlobalCache: true

# Developer experience
preferInteractive: true
progressBarStyle: patrick

# Build optimization
compressionLevel: mixed

# Git integration
changesetIgnorePatterns:
  - "**/*.tsbuildinfo"

