version: "3.9"

services:
    backend:
        image: node:24-bookworm-slim
        working_dir: /app
        command: sh -lc "apt-get update && apt-get install -y --no-install-recommends build-essential python3 && rm -rf /var/lib/apt/lists/* && corepack enable && yarn install --immutable && yarn backend:run"
        environment:
            - DRIFELLASCAPE_BACKEND_REFRESH_MS=30000
        volumes:
            - ./:/app
            - ./logs:/app/logs
        restart: unless-stopped

    worker:
        image: node:24-bookworm-slim
        working_dir: /app
        command: sh -lc "apt-get update && apt-get install -y --no-install-recommends build-essential python3 && rm -rf /var/lib/apt/lists/* && corepack enable && yarn install --immutable && yarn worker:run"
        environment:
            - DRIFELLASCAPE_SYNC_INTERVAL_MS=30000
        volumes:
            - ./:/app
            - ./logs:/app/logs
        depends_on:
            - backend
        restart: unless-stopped

    frontend:
        image: node:24-bookworm-slim
        working_dir: /app
        environment:
            - VITE_API_BASE=
        command: sh -lc "apt-get update && apt-get install -y --no-install-recommends build-essential python3 && rm -rf /var/lib/apt/lists/* && corepack enable && yarn install --immutable && yarn workspace @drifellascape/frontend build && yarn workspace @drifellascape/frontend preview --host 0.0.0.0 --port 4173"
        volumes:
            - ./:/app
        expose:
            - "4173"
        restart: unless-stopped

    frontend-build:
        image: node:24-bookworm-slim
        working_dir: /app
        command: >-
            bash -lc "set -euo pipefail &&
            apt-get update &&
            apt-get install -y --no-install-recommends build-essential python3 &&
            rm -rf /var/lib/apt/lists/* &&
            export COREPACK_ENABLE_DOWNLOAD_PROMPT=0 &&
            corepack enable &&
            yarn install --immutable &&
            if [ -z \"$${RELEASE_ID:-}\" ]; then echo 'RELEASE_ID is required' >&2; exit 1; fi &&
            rm -rf /app/releases/\"$${RELEASE_ID}\" &&
            mkdir -p /app/releases/\"$${RELEASE_ID}\" &&
            yarn workspace @drifellascape/frontend build --outDir /app/releases/\"$${RELEASE_ID}\""
        volumes:
            - ./:/app

    caddy:
        image: caddy:2-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy_data:/data
            - caddy_config:/config
            - ./releases:/srv/releases:ro
            - ./frontend/static:/srv/static:ro
        depends_on:
            - backend
        restart: unless-stopped

    caddy-verify:
        image: caddy:2-alpine
        profiles:
            - verify
        ports:
            - "8080:8080"
        volumes:
            - ./Caddyfile.verify:/etc/caddy/Caddyfile:ro
            - ./releases:/srv/releases:ro
            - ./frontend/static:/srv/static:ro
        depends_on:
            - backend
        restart: unless-stopped

volumes:
    caddy_data:
    caddy_config:
