apiVersion: 1

datasources:
    - name: Pyroscope
      uid: pyroscope
      type: grafana-pyroscope-datasource
      access: proxy
      url: http://127.0.0.1:42833
      isDefault: false
      editable: true
