server:
    http_listen_port: 42831

distributor:
    receivers:
        otlp:
            protocols:
                http:
                    endpoint: 0.0.0.0:42832

ingester:
    max_block_duration: 5m
    complete_block_timeout: 5m

compactor:
    compaction:
        block_retention: 24h

storage:
    trace:
        backend: local
        wal:
            path: /var/tempo/wal
        local:
            path: /var/tempo/blocks

overrides:
    defaults: {}
